version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.0

commands:
  persist_workspace:
    steps:
      - persist_to_workspace:
          root: ~/
          paths:
            - ./

  restore_workspace:
    steps:
      - attach_workspace:
          at: ./

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: yarn install
      - run:
          command: yarn build
      - persist_workspace

  deploy:
    docker:
      - image: cibuilds/aws:2.1.36
    steps:
      - restore_workspace
      - run:
          command: |
            aws s3 sync build/ "s3://toolofjoy.online" --region ap-southeast-2

workflows:
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build